# To run with Docker keep host as db.
# To run without Docker keep host as localhost.
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  # host: localhost
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: dev-transactions_stores

test:
  <<: *default
  database: test-transactions_stores

production:
  <<: *default
  database: production-transactions_stores
